#!/usr/bin/env python3
"""
xacro_nocomment.py : expand xacro, then strip XML comments from the output.

WHY THIS IS NECESSARY
=====================
gazebo_ros2_control does not read the robot description from a topic or a
parameter file. It fetches the URDF string from robot_state_publisher and
then RE-PASSES it to the controller_manager node it creates, as a command
line parameter override:

    --ros-args --param robot_description:=<the entire URDF text>

rcl parses the right hand side of a `--param` rule with a YAML scalar
parser. YAML is whitespace and punctuation sensitive, so a URDF carrying
prose comments can be misread as YAML structure. Two constructs in
particular are fatal:

    a line ending in ":"  followed by an indented line
        -> YAML sees the start of a nested mapping

    the "|" character
        -> YAML's literal block scalar indicator

The autogenerated xacro banner contains "|" on every line, and any comment
containing a sentence like "it does three things:" supplies the first case.
The result is:

    [ERROR] [gazebo_ros2_control]: parser error
    Couldn't parse parameter override rule: '--param robot_description:=...

...and then NO controller_manager is ever created, which surfaces much later
and much less helpfully as:

    Could not contact service /controller_manager/list_controllers

WHY STRIP RATHER THAN DELETE THE COMMENTS
=========================================
The comments are the documentation of the model. Removing them from source
to satisfy a downstream parser would be optimising the wrong thing. Comments
are, by definition, semantically irrelevant to the URDF, so removing them
from the GENERATED artefact loses nothing.

This is the general principle: keep source readable, sanitise at the
boundary.

USAGE
=====
Drop-in replacement for `xacro`, taking the same arguments:

    python3 xacro_nocomment.py model.urdf.xacro sim:=true
"""

import re
import subprocess
import sys


def main() -> int:
    if len(sys.argv) < 2:
        print("usage: xacro_nocomment.py <file.xacro> [args...]", file=sys.stderr)
        return 2

    try:
        expanded = subprocess.run(
            ["xacro"] + sys.argv[1:],
            check=True,
            capture_output=True,
            text=True,
        ).stdout
    except FileNotFoundError:
        print("error: 'xacro' not on PATH. Source your ROS 2 setup.", file=sys.stderr)
        return 1
    except subprocess.CalledProcessError as exc:
        # Forward xacro's own diagnostics unchanged; they are what the user
        # needs to see, and they already carry file and line numbers.
        sys.stderr.write(exc.stderr)
        return exc.returncode

    # Remove every XML comment. DOTALL so multi-line comment bodies match.
    # Comments cannot nest in XML, so a non-greedy match is exact here.
    stripped = re.sub(r"<!--.*?-->", "", expanded, flags=re.DOTALL)

    # Collapse the blank lines the removal leaves behind. Purely cosmetic,
    # but it also shortens the command line, and there IS a length limit on
    # process arguments (ARG_MAX). A 25-link robot with full commentary can
    # approach it.
    stripped = re.sub(r"\n\s*\n+", "\n", stripped)

    sys.stdout.write(stripped)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
